version: "3.3"

services:
  app:
    build: .
    ports:
      - "1234:1234"
    depends_on:
      - db
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=my-secret-pw
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=my-database
    command: ""

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my-database
    volumes:
      - mysql-data:/var/lib/mysql
    command:  bash -c "mysql -u root -p my-secret-pw mydatabase < /app/setup/setup_table.sql"

volumes:
  mysql-data:
    


